#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 11
#define STATE_COUNT 76
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 36
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 9
#define MAX_ALIAS_SEQUENCE_LENGTH 8

enum {
  sym_identifier = 1,
  sym_comment = 2,
  sym_doc_comment = 3,
  anon_sym_import = 4,
  anon_sym_as = 5,
  anon_sym_from = 6,
  sym_wildcard_import = 7,
  anon_sym_DOT = 8,
  anon_sym_COMMA = 9,
  anon_sym_func = 10,
  anon_sym_DASH_GT = 11,
  anon_sym_LBRACE = 12,
  anon_sym_RBRACE = 13,
  anon_sym_class = 14,
  anon_sym_extends = 15,
  sym_number = 16,
  sym_muonscript_module = 17,
  sym_doc_comment_block = 18,
  sym__statement = 19,
  sym_import_statement = 20,
  sym_import_from_statement = 21,
  sym_dotted_name = 22,
  sym_module_member_import = 23,
  sym_imported_module_members = 24,
  sym_named_function_definition = 25,
  sym_class_definition = 26,
  sym_parents_list = 27,
  sym_suite = 28,
  sym_class_suite = 29,
  aux_sym_muonscript_module_repeat1 = 30,
  aux_sym_doc_comment_block_repeat1 = 31,
  aux_sym_dotted_name_repeat1 = 32,
  aux_sym_imported_module_members_repeat1 = 33,
  aux_sym_parents_list_repeat1 = 34,
  aux_sym_class_suite_repeat1 = 35,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_comment] = "comment",
  [sym_doc_comment] = "doc_comment",
  [anon_sym_import] = "import",
  [anon_sym_as] = "as",
  [anon_sym_from] = "from",
  [sym_wildcard_import] = "wildcard_import",
  [anon_sym_DOT] = ".",
  [anon_sym_COMMA] = ",",
  [anon_sym_func] = "func",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_class] = "class",
  [anon_sym_extends] = "extends",
  [sym_number] = "number",
  [sym_muonscript_module] = "muonscript_module",
  [sym_doc_comment_block] = "doc_comment_block",
  [sym__statement] = "_statement",
  [sym_import_statement] = "import_statement",
  [sym_import_from_statement] = "import_from_statement",
  [sym_dotted_name] = "dotted_name",
  [sym_module_member_import] = "module_member_import",
  [sym_imported_module_members] = "imported_module_members",
  [sym_named_function_definition] = "named_function_definition",
  [sym_class_definition] = "class_definition",
  [sym_parents_list] = "parents_list",
  [sym_suite] = "suite",
  [sym_class_suite] = "class_suite",
  [aux_sym_muonscript_module_repeat1] = "muonscript_module_repeat1",
  [aux_sym_doc_comment_block_repeat1] = "doc_comment_block_repeat1",
  [aux_sym_dotted_name_repeat1] = "dotted_name_repeat1",
  [aux_sym_imported_module_members_repeat1] = "imported_module_members_repeat1",
  [aux_sym_parents_list_repeat1] = "parents_list_repeat1",
  [aux_sym_class_suite_repeat1] = "class_suite_repeat1",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_comment] = sym_comment,
  [sym_doc_comment] = sym_doc_comment,
  [anon_sym_import] = anon_sym_import,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_from] = anon_sym_from,
  [sym_wildcard_import] = sym_wildcard_import,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_func] = anon_sym_func,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_class] = anon_sym_class,
  [anon_sym_extends] = anon_sym_extends,
  [sym_number] = sym_number,
  [sym_muonscript_module] = sym_muonscript_module,
  [sym_doc_comment_block] = sym_doc_comment_block,
  [sym__statement] = sym__statement,
  [sym_import_statement] = sym_import_statement,
  [sym_import_from_statement] = sym_import_from_statement,
  [sym_dotted_name] = sym_dotted_name,
  [sym_module_member_import] = sym_module_member_import,
  [sym_imported_module_members] = sym_imported_module_members,
  [sym_named_function_definition] = sym_named_function_definition,
  [sym_class_definition] = sym_class_definition,
  [sym_parents_list] = sym_parents_list,
  [sym_suite] = sym_suite,
  [sym_class_suite] = sym_class_suite,
  [aux_sym_muonscript_module_repeat1] = aux_sym_muonscript_module_repeat1,
  [aux_sym_doc_comment_block_repeat1] = aux_sym_doc_comment_block_repeat1,
  [aux_sym_dotted_name_repeat1] = aux_sym_dotted_name_repeat1,
  [aux_sym_imported_module_members_repeat1] = aux_sym_imported_module_members_repeat1,
  [aux_sym_parents_list_repeat1] = aux_sym_parents_list_repeat1,
  [aux_sym_class_suite_repeat1] = aux_sym_class_suite_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_doc_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_from] = {
    .visible = true,
    .named = false,
  },
  [sym_wildcard_import] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_func] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_class] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_extends] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_muonscript_module] = {
    .visible = true,
    .named = true,
  },
  [sym_doc_comment_block] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_import_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_import_from_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_dotted_name] = {
    .visible = true,
    .named = true,
  },
  [sym_module_member_import] = {
    .visible = true,
    .named = true,
  },
  [sym_imported_module_members] = {
    .visible = true,
    .named = true,
  },
  [sym_named_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_class_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_parents_list] = {
    .visible = true,
    .named = true,
  },
  [sym_suite] = {
    .visible = true,
    .named = true,
  },
  [sym_class_suite] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_muonscript_module_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_doc_comment_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dotted_name_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_imported_module_members_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parents_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_class_suite_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_alias = 1,
  field_doc = 2,
  field_imported_members = 3,
  field_module_member = 4,
  field_module_path = 5,
  field_name = 6,
  field_parents = 7,
  field_return_type = 8,
  field_suite = 9,
};

static const char *ts_field_names[] = {
  [0] = NULL,
  [field_alias] = "alias",
  [field_doc] = "doc",
  [field_imported_members] = "imported_members",
  [field_module_member] = "module_member",
  [field_module_path] = "module_path",
  [field_name] = "name",
  [field_parents] = "parents",
  [field_return_type] = "return_type",
  [field_suite] = "suite",
};

static const TSFieldMapSlice ts_field_map_slices[20] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 8, .length = 1},
  [7] = {.index = 9, .length = 1},
  [8] = {.index = 10, .length = 2},
  [9] = {.index = 12, .length = 2},
  [10] = {.index = 14, .length = 2},
  [11] = {.index = 16, .length = 2},
  [12] = {.index = 18, .length = 3},
  [13] = {.index = 21, .length = 2},
  [14] = {.index = 23, .length = 3},
  [15] = {.index = 26, .length = 3},
  [16] = {.index = 29, .length = 3},
  [17] = {.index = 32, .length = 3},
  [18] = {.index = 35, .length = 4},
  [19] = {.index = 39, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_module_path, 1},
  [2] =
    {field_name, 0},
    {field_name, 1},
  [4] =
    {field_alias, 3},
    {field_module_path, 1},
  [6] =
    {field_imported_members, 3},
    {field_module_path, 1},
  [8] =
    {field_module_member, 0},
  [9] =
    {field_name, 1},
  [10] =
    {field_doc, 3},
    {field_name, 1},
  [12] =
    {field_name, 1},
    {field_suite, 3},
  [14] =
    {field_alias, 2},
    {field_module_member, 0},
  [16] =
    {field_name, 1},
    {field_return_type, 3},
  [18] =
    {field_doc, 3},
    {field_name, 1},
    {field_suite, 4},
  [21] =
    {field_name, 1},
    {field_parents, 3},
  [23] =
    {field_doc, 5},
    {field_name, 1},
    {field_return_type, 3},
  [26] =
    {field_name, 1},
    {field_return_type, 3},
    {field_suite, 5},
  [29] =
    {field_doc, 5},
    {field_name, 1},
    {field_parents, 3},
  [32] =
    {field_name, 1},
    {field_parents, 3},
    {field_suite, 5},
  [35] =
    {field_doc, 5},
    {field_name, 1},
    {field_return_type, 3},
    {field_suite, 6},
  [39] =
    {field_doc, 5},
    {field_name, 1},
    {field_parents, 3},
    {field_suite, 6},
};

static TSSymbol ts_alias_sequences[20][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(4);
      if (lookahead == '*') ADVANCE(7);
      if (lookahead == ',') ADVANCE(9);
      if (lookahead == '-') ADVANCE(3);
      if (lookahead == '.') ADVANCE(8);
      if (lookahead == '/') ADVANCE(1);
      if (lookahead == '{') ADVANCE(11);
      if (lookahead == '}') ADVANCE(12);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 1:
      if (lookahead == '/') ADVANCE(2);
      END_STATE();
    case 2:
      if (lookahead == '/') ADVANCE(6);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 3:
      if (lookahead == '>') ADVANCE(10);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(5);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_doc_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(6);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_wildcard_import);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'a') ADVANCE(1);
      if (lookahead == 'c') ADVANCE(2);
      if (lookahead == 'e') ADVANCE(3);
      if (lookahead == 'f') ADVANCE(4);
      if (lookahead == 'i') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 's') ADVANCE(6);
      END_STATE();
    case 2:
      if (lookahead == 'l') ADVANCE(7);
      END_STATE();
    case 3:
      if (lookahead == 'x') ADVANCE(8);
      END_STATE();
    case 4:
      if (lookahead == 'r') ADVANCE(9);
      if (lookahead == 'u') ADVANCE(10);
      END_STATE();
    case 5:
      if (lookahead == 'm') ADVANCE(11);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(12);
      END_STATE();
    case 8:
      if (lookahead == 't') ADVANCE(13);
      END_STATE();
    case 9:
      if (lookahead == 'o') ADVANCE(14);
      END_STATE();
    case 10:
      if (lookahead == 'n') ADVANCE(15);
      END_STATE();
    case 11:
      if (lookahead == 'p') ADVANCE(16);
      END_STATE();
    case 12:
      if (lookahead == 's') ADVANCE(17);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 14:
      if (lookahead == 'm') ADVANCE(19);
      END_STATE();
    case 15:
      if (lookahead == 'c') ADVANCE(20);
      END_STATE();
    case 16:
      if (lookahead == 'o') ADVANCE(21);
      END_STATE();
    case 17:
      if (lookahead == 's') ADVANCE(22);
      END_STATE();
    case 18:
      if (lookahead == 'n') ADVANCE(23);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_from);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_func);
      END_STATE();
    case 21:
      if (lookahead == 'r') ADVANCE(24);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_class);
      END_STATE();
    case 23:
      if (lookahead == 'd') ADVANCE(25);
      END_STATE();
    case 24:
      if (lookahead == 't') ADVANCE(26);
      END_STATE();
    case 25:
      if (lookahead == 's') ADVANCE(27);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_import);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_extends);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_doc_comment] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_from] = ACTIONS(1),
    [sym_wildcard_import] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_func] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_class] = ACTIONS(1),
    [anon_sym_extends] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
  },
  [1] = {
    [sym_muonscript_module] = STATE(73),
    [sym__statement] = STATE(7),
    [sym_import_statement] = STATE(7),
    [sym_import_from_statement] = STATE(7),
    [sym_named_function_definition] = STATE(7),
    [sym_class_definition] = STATE(7),
    [aux_sym_muonscript_module_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [anon_sym_import] = ACTIONS(7),
    [anon_sym_from] = ACTIONS(9),
    [anon_sym_func] = ACTIONS(11),
    [anon_sym_class] = ACTIONS(13),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_import,
    ACTIONS(9), 1,
      anon_sym_from,
    ACTIONS(11), 1,
      anon_sym_func,
    ACTIONS(13), 1,
      anon_sym_class,
    ACTIONS(15), 1,
      sym_doc_comment,
    ACTIONS(17), 1,
      anon_sym_RBRACE,
    STATE(6), 1,
      sym_doc_comment_block,
    STATE(20), 1,
      aux_sym_doc_comment_block_repeat1,
    STATE(70), 1,
      sym_suite,
    STATE(9), 6,
      sym__statement,
      sym_import_statement,
      sym_import_from_statement,
      sym_named_function_definition,
      sym_class_definition,
      aux_sym_muonscript_module_repeat1,
  [39] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_import,
    ACTIONS(9), 1,
      anon_sym_from,
    ACTIONS(11), 1,
      anon_sym_func,
    ACTIONS(13), 1,
      anon_sym_class,
    ACTIONS(15), 1,
      sym_doc_comment,
    ACTIONS(19), 1,
      anon_sym_RBRACE,
    STATE(4), 1,
      sym_doc_comment_block,
    STATE(20), 1,
      aux_sym_doc_comment_block_repeat1,
    STATE(60), 1,
      sym_suite,
    STATE(9), 6,
      sym__statement,
      sym_import_statement,
      sym_import_from_statement,
      sym_named_function_definition,
      sym_class_definition,
      aux_sym_muonscript_module_repeat1,
  [78] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_import,
    ACTIONS(9), 1,
      anon_sym_from,
    ACTIONS(11), 1,
      anon_sym_func,
    ACTIONS(13), 1,
      anon_sym_class,
    ACTIONS(21), 1,
      anon_sym_RBRACE,
    STATE(69), 1,
      sym_suite,
    STATE(9), 6,
      sym__statement,
      sym_import_statement,
      sym_import_from_statement,
      sym_named_function_definition,
      sym_class_definition,
      aux_sym_muonscript_module_repeat1,
  [108] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_import,
    ACTIONS(28), 1,
      anon_sym_from,
    ACTIONS(31), 1,
      anon_sym_func,
    ACTIONS(34), 1,
      anon_sym_class,
    ACTIONS(23), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    STATE(5), 6,
      sym__statement,
      sym_import_statement,
      sym_import_from_statement,
      sym_named_function_definition,
      sym_class_definition,
      aux_sym_muonscript_module_repeat1,
  [136] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_import,
    ACTIONS(9), 1,
      anon_sym_from,
    ACTIONS(11), 1,
      anon_sym_func,
    ACTIONS(13), 1,
      anon_sym_class,
    ACTIONS(37), 1,
      anon_sym_RBRACE,
    STATE(59), 1,
      sym_suite,
    STATE(9), 6,
      sym__statement,
      sym_import_statement,
      sym_import_from_statement,
      sym_named_function_definition,
      sym_class_definition,
      aux_sym_muonscript_module_repeat1,
  [166] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_import,
    ACTIONS(9), 1,
      anon_sym_from,
    ACTIONS(11), 1,
      anon_sym_func,
    ACTIONS(13), 1,
      anon_sym_class,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    STATE(5), 6,
      sym__statement,
      sym_import_statement,
      sym_import_from_statement,
      sym_named_function_definition,
      sym_class_definition,
      aux_sym_muonscript_module_repeat1,
  [193] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      anon_sym_DOT,
    STATE(10), 1,
      aux_sym_dotted_name_repeat1,
    ACTIONS(41), 9,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_as,
      anon_sym_from,
      anon_sym_COMMA,
      anon_sym_func,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_class,
  [214] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_import,
    ACTIONS(9), 1,
      anon_sym_from,
    ACTIONS(11), 1,
      anon_sym_func,
    ACTIONS(13), 1,
      anon_sym_class,
    ACTIONS(45), 1,
      anon_sym_RBRACE,
    STATE(5), 6,
      sym__statement,
      sym_import_statement,
      sym_import_from_statement,
      sym_named_function_definition,
      sym_class_definition,
      aux_sym_muonscript_module_repeat1,
  [241] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      anon_sym_DOT,
    STATE(11), 1,
      aux_sym_dotted_name_repeat1,
    ACTIONS(47), 9,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_as,
      anon_sym_from,
      anon_sym_COMMA,
      anon_sym_func,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_class,
  [262] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      anon_sym_DOT,
    STATE(11), 1,
      aux_sym_dotted_name_repeat1,
    ACTIONS(49), 9,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_as,
      anon_sym_from,
      anon_sym_COMMA,
      anon_sym_func,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_class,
  [283] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 10,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_as,
      anon_sym_from,
      anon_sym_DOT,
      anon_sym_COMMA,
      anon_sym_func,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_class,
  [299] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 1,
      anon_sym_COMMA,
    STATE(13), 1,
      aux_sym_imported_module_members_repeat1,
    ACTIONS(54), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_from,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [317] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_func,
    ACTIONS(15), 1,
      sym_doc_comment,
    ACTIONS(59), 1,
      anon_sym_RBRACE,
    STATE(20), 1,
      aux_sym_doc_comment_block_repeat1,
    STATE(43), 1,
      sym_doc_comment_block,
    STATE(67), 1,
      sym_class_suite,
    STATE(46), 2,
      sym_named_function_definition,
      aux_sym_class_suite_repeat1,
  [343] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 1,
      anon_sym_COMMA,
    STATE(13), 1,
      aux_sym_imported_module_members_repeat1,
    ACTIONS(61), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_from,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [361] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_func,
    ACTIONS(15), 1,
      sym_doc_comment,
    ACTIONS(65), 1,
      anon_sym_RBRACE,
    STATE(20), 1,
      aux_sym_doc_comment_block_repeat1,
    STATE(42), 1,
      sym_doc_comment_block,
    STATE(61), 1,
      sym_class_suite,
    STATE(46), 2,
      sym_named_function_definition,
      aux_sym_class_suite_repeat1,
  [387] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      anon_sym_as,
    ACTIONS(67), 7,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_from,
      anon_sym_COMMA,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [403] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 1,
      anon_sym_COMMA,
    STATE(15), 1,
      aux_sym_imported_module_members_repeat1,
    ACTIONS(71), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_from,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [421] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(54), 7,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_from,
      anon_sym_COMMA,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [434] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      sym_doc_comment,
    STATE(22), 1,
      aux_sym_doc_comment_block_repeat1,
    ACTIONS(75), 5,
      anon_sym_import,
      anon_sym_from,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [451] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 7,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_from,
      anon_sym_COMMA,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [464] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(79), 1,
      sym_doc_comment,
    STATE(22), 1,
      aux_sym_doc_comment_block_repeat1,
    ACTIONS(82), 5,
      anon_sym_import,
      anon_sym_from,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [481] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 1,
      anon_sym_as,
    ACTIONS(84), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_from,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [496] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_from,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [508] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_from,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [520] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_from,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [532] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_from,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [544] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_from,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [556] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_from,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [568] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(100), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_from,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [580] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_from,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [592] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_from,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [604] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_from,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [616] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_from,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [628] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_from,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [640] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_from,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [652] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_from,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [664] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(116), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_from,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [676] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_from,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [688] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(120), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_from,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [700] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_from,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [712] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_func,
    ACTIONS(124), 1,
      anon_sym_RBRACE,
    STATE(72), 1,
      sym_class_suite,
    STATE(46), 2,
      sym_named_function_definition,
      aux_sym_class_suite_repeat1,
  [729] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_func,
    ACTIONS(126), 1,
      anon_sym_RBRACE,
    STATE(75), 1,
      sym_class_suite,
    STATE(46), 2,
      sym_named_function_definition,
      aux_sym_class_suite_repeat1,
  [746] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(128), 1,
      anon_sym_func,
    ACTIONS(131), 1,
      anon_sym_RBRACE,
    STATE(44), 2,
      sym_named_function_definition,
      aux_sym_class_suite_repeat1,
  [760] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      sym_identifier,
    ACTIONS(135), 1,
      sym_wildcard_import,
    STATE(18), 1,
      sym_module_member_import,
    STATE(29), 1,
      sym_imported_module_members,
  [776] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_func,
    ACTIONS(137), 1,
      anon_sym_RBRACE,
    STATE(44), 2,
      sym_named_function_definition,
      aux_sym_class_suite_repeat1,
  [790] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      anon_sym_COMMA,
    ACTIONS(141), 1,
      anon_sym_LBRACE,
    STATE(49), 1,
      aux_sym_parents_list_repeat1,
  [803] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      sym_identifier,
    STATE(47), 1,
      sym_dotted_name,
    STATE(63), 1,
      sym_parents_list,
  [816] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      anon_sym_COMMA,
    ACTIONS(145), 1,
      anon_sym_LBRACE,
    STATE(50), 1,
      aux_sym_parents_list_repeat1,
  [829] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 1,
      anon_sym_COMMA,
    ACTIONS(150), 1,
      anon_sym_LBRACE,
    STATE(50), 1,
      aux_sym_parents_list_repeat1,
  [842] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 2,
      anon_sym_COMMA,
      anon_sym_LBRACE,
  [850] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      sym_identifier,
    STATE(71), 1,
      sym_dotted_name,
  [860] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 1,
      anon_sym_DASH_GT,
    ACTIONS(154), 1,
      anon_sym_LBRACE,
  [870] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      sym_identifier,
    STATE(51), 1,
      sym_dotted_name,
  [880] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      sym_identifier,
    STATE(23), 1,
      sym_dotted_name,
  [890] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      sym_identifier,
    STATE(74), 1,
      sym_dotted_name,
  [900] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      sym_identifier,
    STATE(19), 1,
      sym_module_member_import,
  [910] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 1,
      anon_sym_LBRACE,
    ACTIONS(158), 1,
      anon_sym_extends,
  [920] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 1,
      anon_sym_RBRACE,
  [927] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 1,
      anon_sym_RBRACE,
  [934] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 1,
      anon_sym_RBRACE,
  [941] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(166), 1,
      sym_identifier,
  [948] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 1,
      anon_sym_LBRACE,
  [955] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(170), 1,
      sym_identifier,
  [962] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 1,
      sym_identifier,
  [969] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 1,
      sym_identifier,
  [976] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(176), 1,
      anon_sym_RBRACE,
  [983] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 1,
      sym_identifier,
  [990] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 1,
      anon_sym_RBRACE,
  [997] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 1,
      anon_sym_RBRACE,
  [1004] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 1,
      anon_sym_LBRACE,
  [1011] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      anon_sym_RBRACE,
  [1018] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(188), 1,
      ts_builtin_sym_end,
  [1025] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 1,
      anon_sym_import,
  [1032] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 1,
      anon_sym_RBRACE,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 39,
  [SMALL_STATE(4)] = 78,
  [SMALL_STATE(5)] = 108,
  [SMALL_STATE(6)] = 136,
  [SMALL_STATE(7)] = 166,
  [SMALL_STATE(8)] = 193,
  [SMALL_STATE(9)] = 214,
  [SMALL_STATE(10)] = 241,
  [SMALL_STATE(11)] = 262,
  [SMALL_STATE(12)] = 283,
  [SMALL_STATE(13)] = 299,
  [SMALL_STATE(14)] = 317,
  [SMALL_STATE(15)] = 343,
  [SMALL_STATE(16)] = 361,
  [SMALL_STATE(17)] = 387,
  [SMALL_STATE(18)] = 403,
  [SMALL_STATE(19)] = 421,
  [SMALL_STATE(20)] = 434,
  [SMALL_STATE(21)] = 451,
  [SMALL_STATE(22)] = 464,
  [SMALL_STATE(23)] = 481,
  [SMALL_STATE(24)] = 496,
  [SMALL_STATE(25)] = 508,
  [SMALL_STATE(26)] = 520,
  [SMALL_STATE(27)] = 532,
  [SMALL_STATE(28)] = 544,
  [SMALL_STATE(29)] = 556,
  [SMALL_STATE(30)] = 568,
  [SMALL_STATE(31)] = 580,
  [SMALL_STATE(32)] = 592,
  [SMALL_STATE(33)] = 604,
  [SMALL_STATE(34)] = 616,
  [SMALL_STATE(35)] = 628,
  [SMALL_STATE(36)] = 640,
  [SMALL_STATE(37)] = 652,
  [SMALL_STATE(38)] = 664,
  [SMALL_STATE(39)] = 676,
  [SMALL_STATE(40)] = 688,
  [SMALL_STATE(41)] = 700,
  [SMALL_STATE(42)] = 712,
  [SMALL_STATE(43)] = 729,
  [SMALL_STATE(44)] = 746,
  [SMALL_STATE(45)] = 760,
  [SMALL_STATE(46)] = 776,
  [SMALL_STATE(47)] = 790,
  [SMALL_STATE(48)] = 803,
  [SMALL_STATE(49)] = 816,
  [SMALL_STATE(50)] = 829,
  [SMALL_STATE(51)] = 842,
  [SMALL_STATE(52)] = 850,
  [SMALL_STATE(53)] = 860,
  [SMALL_STATE(54)] = 870,
  [SMALL_STATE(55)] = 880,
  [SMALL_STATE(56)] = 890,
  [SMALL_STATE(57)] = 900,
  [SMALL_STATE(58)] = 910,
  [SMALL_STATE(59)] = 920,
  [SMALL_STATE(60)] = 927,
  [SMALL_STATE(61)] = 934,
  [SMALL_STATE(62)] = 941,
  [SMALL_STATE(63)] = 948,
  [SMALL_STATE(64)] = 955,
  [SMALL_STATE(65)] = 962,
  [SMALL_STATE(66)] = 969,
  [SMALL_STATE(67)] = 976,
  [SMALL_STATE(68)] = 983,
  [SMALL_STATE(69)] = 990,
  [SMALL_STATE(70)] = 997,
  [SMALL_STATE(71)] = 1004,
  [SMALL_STATE(72)] = 1011,
  [SMALL_STATE(73)] = 1018,
  [SMALL_STATE(74)] = 1025,
  [SMALL_STATE(75)] = 1032,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_muonscript_module, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_muonscript_module_repeat1, 2),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_muonscript_module_repeat1, 2), SHIFT_REPEAT(55),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_muonscript_module_repeat1, 2), SHIFT_REPEAT(56),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_muonscript_module_repeat1, 2), SHIFT_REPEAT(65),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_muonscript_module_repeat1, 2), SHIFT_REPEAT(66),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_muonscript_module, 1),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dotted_name, 1, .production_id = 1),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_suite, 1),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dotted_name, 2, .production_id = 3),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dotted_name_repeat1, 2),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dotted_name_repeat1, 2), SHIFT_REPEAT(68),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_imported_module_members_repeat1, 2),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_imported_module_members_repeat1, 2), SHIFT_REPEAT(57),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_imported_module_members, 2),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_member_import, 1, .production_id = 6),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_imported_module_members, 1),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doc_comment_block, 1),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_member_import, 3, .production_id = 10),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_doc_comment_block_repeat1, 2), SHIFT_REPEAT(22),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_doc_comment_block_repeat1, 2),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_statement, 2, .production_id = 2),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_definition, 5, .production_id = 8),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_definition, 6, .production_id = 12),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_definition, 8, .production_id = 19),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_function_definition, 8, .production_id = 18),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_definition, 7, .production_id = 17),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_from_statement, 4, .production_id = 5),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_definition, 5, .production_id = 9),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_function_definition, 4, .production_id = 7),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_function_definition, 7, .production_id = 15),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_function_definition, 7, .production_id = 14),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_definition, 4, .production_id = 7),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_definition, 6, .production_id = 13),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_function_definition, 6, .production_id = 12),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_function_definition, 6, .production_id = 11),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_definition, 7, .production_id = 16),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_statement, 4, .production_id = 4),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_function_definition, 5, .production_id = 9),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_function_definition, 5, .production_id = 8),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [128] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_class_suite_repeat1, 2), SHIFT_REPEAT(65),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_class_suite_repeat1, 2),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_suite, 1),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parents_list, 1),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parents_list, 2),
  [147] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parents_list_repeat1, 2), SHIFT_REPEAT(54),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parents_list_repeat1, 2),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [188] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_muonscript(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const unsigned short *)ts_parse_table,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .symbol_names = ts_symbol_names,
    .public_symbol_map = ts_symbol_map,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .field_count = FIELD_COUNT,
    .field_names = ts_field_names,
    .field_map_slices = (const TSFieldMapSlice *)ts_field_map_slices,
    .field_map_entries = (const TSFieldMapEntry *)ts_field_map_entries,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
