#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 11
#define STATE_COUNT 61
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 32
#define ALIAS_COUNT 0
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 8
#define MAX_ALIAS_SEQUENCE_LENGTH 8

enum {
  sym_identifier = 1,
  sym_comment = 2,
  sym_doc_comment = 3,
  anon_sym_import = 4,
  anon_sym_as = 5,
  anon_sym_from = 6,
  anon_sym_DOT = 7,
  anon_sym_COMMA = 8,
  anon_sym_func = 9,
  anon_sym_DASH_GT = 10,
  anon_sym_LBRACE = 11,
  anon_sym_RBRACE = 12,
  anon_sym_class = 13,
  sym_number = 14,
  sym_muonscript_module = 15,
  sym_doc_comment_block = 16,
  sym__statement = 17,
  sym_import_statement = 18,
  sym_import_from_statement = 19,
  sym_dotted_name = 20,
  sym_module_member_import = 21,
  sym_imported_module_members = 22,
  sym_named_function_definition = 23,
  sym_class_definition = 24,
  sym_suite = 25,
  sym_class_suite = 26,
  aux_sym_muonscript_module_repeat1 = 27,
  aux_sym_doc_comment_block_repeat1 = 28,
  aux_sym_dotted_name_repeat1 = 29,
  aux_sym_imported_module_members_repeat1 = 30,
  aux_sym_class_suite_repeat1 = 31,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_comment] = "comment",
  [sym_doc_comment] = "doc_comment",
  [anon_sym_import] = "import",
  [anon_sym_as] = "as",
  [anon_sym_from] = "from",
  [anon_sym_DOT] = ".",
  [anon_sym_COMMA] = ",",
  [anon_sym_func] = "func",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_class] = "class",
  [sym_number] = "number",
  [sym_muonscript_module] = "muonscript_module",
  [sym_doc_comment_block] = "doc_comment_block",
  [sym__statement] = "_statement",
  [sym_import_statement] = "import_statement",
  [sym_import_from_statement] = "import_from_statement",
  [sym_dotted_name] = "dotted_name",
  [sym_module_member_import] = "module_member_import",
  [sym_imported_module_members] = "imported_module_members",
  [sym_named_function_definition] = "named_function_definition",
  [sym_class_definition] = "class_definition",
  [sym_suite] = "suite",
  [sym_class_suite] = "class_suite",
  [aux_sym_muonscript_module_repeat1] = "muonscript_module_repeat1",
  [aux_sym_doc_comment_block_repeat1] = "doc_comment_block_repeat1",
  [aux_sym_dotted_name_repeat1] = "dotted_name_repeat1",
  [aux_sym_imported_module_members_repeat1] = "imported_module_members_repeat1",
  [aux_sym_class_suite_repeat1] = "class_suite_repeat1",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_comment] = sym_comment,
  [sym_doc_comment] = sym_doc_comment,
  [anon_sym_import] = anon_sym_import,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_from] = anon_sym_from,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_func] = anon_sym_func,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_class] = anon_sym_class,
  [sym_number] = sym_number,
  [sym_muonscript_module] = sym_muonscript_module,
  [sym_doc_comment_block] = sym_doc_comment_block,
  [sym__statement] = sym__statement,
  [sym_import_statement] = sym_import_statement,
  [sym_import_from_statement] = sym_import_from_statement,
  [sym_dotted_name] = sym_dotted_name,
  [sym_module_member_import] = sym_module_member_import,
  [sym_imported_module_members] = sym_imported_module_members,
  [sym_named_function_definition] = sym_named_function_definition,
  [sym_class_definition] = sym_class_definition,
  [sym_suite] = sym_suite,
  [sym_class_suite] = sym_class_suite,
  [aux_sym_muonscript_module_repeat1] = aux_sym_muonscript_module_repeat1,
  [aux_sym_doc_comment_block_repeat1] = aux_sym_doc_comment_block_repeat1,
  [aux_sym_dotted_name_repeat1] = aux_sym_dotted_name_repeat1,
  [aux_sym_imported_module_members_repeat1] = aux_sym_imported_module_members_repeat1,
  [aux_sym_class_suite_repeat1] = aux_sym_class_suite_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_doc_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_from] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_func] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_class] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_muonscript_module] = {
    .visible = true,
    .named = true,
  },
  [sym_doc_comment_block] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_import_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_import_from_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_dotted_name] = {
    .visible = true,
    .named = true,
  },
  [sym_module_member_import] = {
    .visible = true,
    .named = true,
  },
  [sym_imported_module_members] = {
    .visible = true,
    .named = true,
  },
  [sym_named_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_class_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_suite] = {
    .visible = true,
    .named = true,
  },
  [sym_class_suite] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_muonscript_module_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_doc_comment_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dotted_name_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_imported_module_members_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_class_suite_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_alias = 1,
  field_doc = 2,
  field_imported_members = 3,
  field_module_member = 4,
  field_module_path = 5,
  field_name = 6,
  field_return_type = 7,
  field_suite = 8,
};

static const char *ts_field_names[] = {
  [0] = NULL,
  [field_alias] = "alias",
  [field_doc] = "doc",
  [field_imported_members] = "imported_members",
  [field_module_member] = "module_member",
  [field_module_path] = "module_path",
  [field_name] = "name",
  [field_return_type] = "return_type",
  [field_suite] = "suite",
};

static const TSFieldMapSlice ts_field_map_slices[16] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 1},
  [6] = {.index = 7, .length = 2},
  [7] = {.index = 9, .length = 1},
  [8] = {.index = 10, .length = 2},
  [9] = {.index = 12, .length = 2},
  [10] = {.index = 14, .length = 2},
  [11] = {.index = 16, .length = 2},
  [12] = {.index = 18, .length = 3},
  [13] = {.index = 21, .length = 3},
  [14] = {.index = 24, .length = 3},
  [15] = {.index = 27, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_module_path, 1},
  [2] =
    {field_name, 0},
    {field_name, 1},
  [4] =
    {field_alias, 3},
    {field_module_path, 1},
  [6] =
    {field_module_member, 0},
  [7] =
    {field_imported_members, 3},
    {field_module_path, 1},
  [9] =
    {field_name, 1},
  [10] =
    {field_doc, 3},
    {field_name, 1},
  [12] =
    {field_name, 1},
    {field_suite, 3},
  [14] =
    {field_alias, 2},
    {field_module_member, 0},
  [16] =
    {field_name, 1},
    {field_return_type, 3},
  [18] =
    {field_doc, 3},
    {field_name, 1},
    {field_suite, 4},
  [21] =
    {field_doc, 5},
    {field_name, 1},
    {field_return_type, 3},
  [24] =
    {field_name, 1},
    {field_return_type, 3},
    {field_suite, 5},
  [27] =
    {field_doc, 5},
    {field_name, 1},
    {field_return_type, 3},
    {field_suite, 6},
};

static TSSymbol ts_alias_sequences[16][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(4);
      if (lookahead == ',') ADVANCE(8);
      if (lookahead == '-') ADVANCE(3);
      if (lookahead == '.') ADVANCE(7);
      if (lookahead == '/') ADVANCE(1);
      if (lookahead == '{') ADVANCE(10);
      if (lookahead == '}') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 1:
      if (lookahead == '/') ADVANCE(2);
      END_STATE();
    case 2:
      if (lookahead == '/') ADVANCE(6);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 3:
      if (lookahead == '>') ADVANCE(9);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(5);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_doc_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(6);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(14);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'a') ADVANCE(1);
      if (lookahead == 'c') ADVANCE(2);
      if (lookahead == 'f') ADVANCE(3);
      if (lookahead == 'i') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 's') ADVANCE(5);
      END_STATE();
    case 2:
      if (lookahead == 'l') ADVANCE(6);
      END_STATE();
    case 3:
      if (lookahead == 'r') ADVANCE(7);
      if (lookahead == 'u') ADVANCE(8);
      END_STATE();
    case 4:
      if (lookahead == 'm') ADVANCE(9);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(10);
      END_STATE();
    case 7:
      if (lookahead == 'o') ADVANCE(11);
      END_STATE();
    case 8:
      if (lookahead == 'n') ADVANCE(12);
      END_STATE();
    case 9:
      if (lookahead == 'p') ADVANCE(13);
      END_STATE();
    case 10:
      if (lookahead == 's') ADVANCE(14);
      END_STATE();
    case 11:
      if (lookahead == 'm') ADVANCE(15);
      END_STATE();
    case 12:
      if (lookahead == 'c') ADVANCE(16);
      END_STATE();
    case 13:
      if (lookahead == 'o') ADVANCE(17);
      END_STATE();
    case 14:
      if (lookahead == 's') ADVANCE(18);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_from);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_func);
      END_STATE();
    case 17:
      if (lookahead == 'r') ADVANCE(19);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_class);
      END_STATE();
    case 19:
      if (lookahead == 't') ADVANCE(20);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_import);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_doc_comment] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_from] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_func] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_class] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
  },
  [1] = {
    [sym_muonscript_module] = STATE(49),
    [sym__statement] = STATE(7),
    [sym_import_statement] = STATE(7),
    [sym_import_from_statement] = STATE(7),
    [sym_named_function_definition] = STATE(7),
    [sym_class_definition] = STATE(7),
    [aux_sym_muonscript_module_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [anon_sym_import] = ACTIONS(7),
    [anon_sym_from] = ACTIONS(9),
    [anon_sym_func] = ACTIONS(11),
    [anon_sym_class] = ACTIONS(13),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_import,
    ACTIONS(9), 1,
      anon_sym_from,
    ACTIONS(11), 1,
      anon_sym_func,
    ACTIONS(13), 1,
      anon_sym_class,
    ACTIONS(15), 1,
      sym_doc_comment,
    ACTIONS(17), 1,
      anon_sym_RBRACE,
    STATE(6), 1,
      sym_doc_comment_block,
    STATE(19), 1,
      aux_sym_doc_comment_block_repeat1,
    STATE(60), 1,
      sym_suite,
    STATE(8), 6,
      sym__statement,
      sym_import_statement,
      sym_import_from_statement,
      sym_named_function_definition,
      sym_class_definition,
      aux_sym_muonscript_module_repeat1,
  [39] = 11,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_import,
    ACTIONS(9), 1,
      anon_sym_from,
    ACTIONS(11), 1,
      anon_sym_func,
    ACTIONS(13), 1,
      anon_sym_class,
    ACTIONS(15), 1,
      sym_doc_comment,
    ACTIONS(19), 1,
      anon_sym_RBRACE,
    STATE(4), 1,
      sym_doc_comment_block,
    STATE(19), 1,
      aux_sym_doc_comment_block_repeat1,
    STATE(54), 1,
      sym_suite,
    STATE(8), 6,
      sym__statement,
      sym_import_statement,
      sym_import_from_statement,
      sym_named_function_definition,
      sym_class_definition,
      aux_sym_muonscript_module_repeat1,
  [78] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_import,
    ACTIONS(9), 1,
      anon_sym_from,
    ACTIONS(11), 1,
      anon_sym_func,
    ACTIONS(13), 1,
      anon_sym_class,
    ACTIONS(21), 1,
      anon_sym_RBRACE,
    STATE(58), 1,
      sym_suite,
    STATE(8), 6,
      sym__statement,
      sym_import_statement,
      sym_import_from_statement,
      sym_named_function_definition,
      sym_class_definition,
      aux_sym_muonscript_module_repeat1,
  [108] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      anon_sym_import,
    ACTIONS(28), 1,
      anon_sym_from,
    ACTIONS(31), 1,
      anon_sym_func,
    ACTIONS(34), 1,
      anon_sym_class,
    ACTIONS(23), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    STATE(5), 6,
      sym__statement,
      sym_import_statement,
      sym_import_from_statement,
      sym_named_function_definition,
      sym_class_definition,
      aux_sym_muonscript_module_repeat1,
  [136] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_import,
    ACTIONS(9), 1,
      anon_sym_from,
    ACTIONS(11), 1,
      anon_sym_func,
    ACTIONS(13), 1,
      anon_sym_class,
    ACTIONS(37), 1,
      anon_sym_RBRACE,
    STATE(46), 1,
      sym_suite,
    STATE(8), 6,
      sym__statement,
      sym_import_statement,
      sym_import_from_statement,
      sym_named_function_definition,
      sym_class_definition,
      aux_sym_muonscript_module_repeat1,
  [166] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_import,
    ACTIONS(9), 1,
      anon_sym_from,
    ACTIONS(11), 1,
      anon_sym_func,
    ACTIONS(13), 1,
      anon_sym_class,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    STATE(5), 6,
      sym__statement,
      sym_import_statement,
      sym_import_from_statement,
      sym_named_function_definition,
      sym_class_definition,
      aux_sym_muonscript_module_repeat1,
  [193] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_import,
    ACTIONS(9), 1,
      anon_sym_from,
    ACTIONS(11), 1,
      anon_sym_func,
    ACTIONS(13), 1,
      anon_sym_class,
    ACTIONS(41), 1,
      anon_sym_RBRACE,
    STATE(5), 6,
      sym__statement,
      sym_import_statement,
      sym_import_from_statement,
      sym_named_function_definition,
      sym_class_definition,
      aux_sym_muonscript_module_repeat1,
  [220] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_DOT,
    STATE(9), 1,
      aux_sym_dotted_name_repeat1,
    ACTIONS(43), 8,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_as,
      anon_sym_from,
      anon_sym_func,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_class,
  [240] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      anon_sym_DOT,
    STATE(11), 1,
      aux_sym_dotted_name_repeat1,
    ACTIONS(48), 8,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_as,
      anon_sym_from,
      anon_sym_func,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_class,
  [260] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(50), 1,
      anon_sym_DOT,
    STATE(9), 1,
      aux_sym_dotted_name_repeat1,
    ACTIONS(52), 8,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_as,
      anon_sym_from,
      anon_sym_func,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_class,
  [280] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 9,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_as,
      anon_sym_from,
      anon_sym_DOT,
      anon_sym_func,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_class,
  [295] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 1,
      anon_sym_COMMA,
    STATE(13), 1,
      aux_sym_imported_module_members_repeat1,
    ACTIONS(54), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_from,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [313] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 1,
      anon_sym_COMMA,
    STATE(16), 1,
      aux_sym_imported_module_members_repeat1,
    ACTIONS(59), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_from,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [331] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_func,
    ACTIONS(15), 1,
      sym_doc_comment,
    ACTIONS(63), 1,
      anon_sym_RBRACE,
    STATE(19), 1,
      aux_sym_doc_comment_block_repeat1,
    STATE(37), 1,
      sym_doc_comment_block,
    STATE(57), 1,
      sym_class_suite,
    STATE(39), 2,
      sym_named_function_definition,
      aux_sym_class_suite_repeat1,
  [357] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 1,
      anon_sym_COMMA,
    STATE(13), 1,
      aux_sym_imported_module_members_repeat1,
    ACTIONS(65), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_from,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [375] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      anon_sym_as,
    ACTIONS(67), 7,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_from,
      anon_sym_COMMA,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [391] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 7,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_from,
      anon_sym_COMMA,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [404] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      sym_doc_comment,
    STATE(21), 1,
      aux_sym_doc_comment_block_repeat1,
    ACTIONS(75), 5,
      anon_sym_import,
      anon_sym_from,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [421] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(54), 7,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_from,
      anon_sym_COMMA,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [434] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(77), 1,
      sym_doc_comment,
    STATE(21), 1,
      aux_sym_doc_comment_block_repeat1,
    ACTIONS(80), 5,
      anon_sym_import,
      anon_sym_from,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [451] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 1,
      anon_sym_as,
    ACTIONS(82), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_from,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [466] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_from,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [478] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_from,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [490] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_from,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [502] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_from,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [514] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_from,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [526] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_from,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [538] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_from,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [550] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(100), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_from,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [562] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_from,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [574] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_from,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [586] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_from,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [598] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(108), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_from,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [610] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_from,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [622] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 6,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_from,
      anon_sym_func,
      anon_sym_RBRACE,
      anon_sym_class,
  [634] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_func,
    ACTIONS(114), 1,
      anon_sym_RBRACE,
    STATE(48), 1,
      sym_class_suite,
    STATE(39), 2,
      sym_named_function_definition,
      aux_sym_class_suite_repeat1,
  [651] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(116), 1,
      anon_sym_func,
    ACTIONS(119), 1,
      anon_sym_RBRACE,
    STATE(38), 2,
      sym_named_function_definition,
      aux_sym_class_suite_repeat1,
  [665] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      anon_sym_func,
    ACTIONS(121), 1,
      anon_sym_RBRACE,
    STATE(38), 2,
      sym_named_function_definition,
      aux_sym_class_suite_repeat1,
  [679] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      sym_identifier,
    STATE(14), 1,
      sym_module_member_import,
    STATE(26), 1,
      sym_imported_module_members,
  [692] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      sym_identifier,
    STATE(22), 1,
      sym_dotted_name,
  [702] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      sym_identifier,
    STATE(52), 1,
      sym_dotted_name,
  [712] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 1,
      sym_identifier,
    STATE(20), 1,
      sym_module_member_import,
  [722] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(127), 1,
      anon_sym_DASH_GT,
    ACTIONS(129), 1,
      anon_sym_LBRACE,
  [732] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(125), 1,
      sym_identifier,
    STATE(47), 1,
      sym_dotted_name,
  [742] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(131), 1,
      anon_sym_RBRACE,
  [749] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(133), 1,
      anon_sym_import,
  [756] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 1,
      anon_sym_RBRACE,
  [763] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 1,
      ts_builtin_sym_end,
  [770] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 1,
      sym_identifier,
  [777] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(141), 1,
      sym_identifier,
  [784] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(143), 1,
      anon_sym_LBRACE,
  [791] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 1,
      anon_sym_LBRACE,
  [798] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 1,
      anon_sym_RBRACE,
  [805] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(149), 1,
      sym_identifier,
  [812] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 1,
      sym_identifier,
  [819] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(153), 1,
      anon_sym_RBRACE,
  [826] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 1,
      anon_sym_RBRACE,
  [833] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 1,
      sym_identifier,
  [840] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 1,
      anon_sym_RBRACE,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 39,
  [SMALL_STATE(4)] = 78,
  [SMALL_STATE(5)] = 108,
  [SMALL_STATE(6)] = 136,
  [SMALL_STATE(7)] = 166,
  [SMALL_STATE(8)] = 193,
  [SMALL_STATE(9)] = 220,
  [SMALL_STATE(10)] = 240,
  [SMALL_STATE(11)] = 260,
  [SMALL_STATE(12)] = 280,
  [SMALL_STATE(13)] = 295,
  [SMALL_STATE(14)] = 313,
  [SMALL_STATE(15)] = 331,
  [SMALL_STATE(16)] = 357,
  [SMALL_STATE(17)] = 375,
  [SMALL_STATE(18)] = 391,
  [SMALL_STATE(19)] = 404,
  [SMALL_STATE(20)] = 421,
  [SMALL_STATE(21)] = 434,
  [SMALL_STATE(22)] = 451,
  [SMALL_STATE(23)] = 466,
  [SMALL_STATE(24)] = 478,
  [SMALL_STATE(25)] = 490,
  [SMALL_STATE(26)] = 502,
  [SMALL_STATE(27)] = 514,
  [SMALL_STATE(28)] = 526,
  [SMALL_STATE(29)] = 538,
  [SMALL_STATE(30)] = 550,
  [SMALL_STATE(31)] = 562,
  [SMALL_STATE(32)] = 574,
  [SMALL_STATE(33)] = 586,
  [SMALL_STATE(34)] = 598,
  [SMALL_STATE(35)] = 610,
  [SMALL_STATE(36)] = 622,
  [SMALL_STATE(37)] = 634,
  [SMALL_STATE(38)] = 651,
  [SMALL_STATE(39)] = 665,
  [SMALL_STATE(40)] = 679,
  [SMALL_STATE(41)] = 692,
  [SMALL_STATE(42)] = 702,
  [SMALL_STATE(43)] = 712,
  [SMALL_STATE(44)] = 722,
  [SMALL_STATE(45)] = 732,
  [SMALL_STATE(46)] = 742,
  [SMALL_STATE(47)] = 749,
  [SMALL_STATE(48)] = 756,
  [SMALL_STATE(49)] = 763,
  [SMALL_STATE(50)] = 770,
  [SMALL_STATE(51)] = 777,
  [SMALL_STATE(52)] = 784,
  [SMALL_STATE(53)] = 791,
  [SMALL_STATE(54)] = 798,
  [SMALL_STATE(55)] = 805,
  [SMALL_STATE(56)] = 812,
  [SMALL_STATE(57)] = 819,
  [SMALL_STATE(58)] = 826,
  [SMALL_STATE(59)] = 833,
  [SMALL_STATE(60)] = 840,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_muonscript_module, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_muonscript_module_repeat1, 2),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_muonscript_module_repeat1, 2), SHIFT_REPEAT(41),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_muonscript_module_repeat1, 2), SHIFT_REPEAT(45),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_muonscript_module_repeat1, 2), SHIFT_REPEAT(51),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_muonscript_module_repeat1, 2), SHIFT_REPEAT(50),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_muonscript_module, 1),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_suite, 1),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dotted_name_repeat1, 2),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dotted_name_repeat1, 2), SHIFT_REPEAT(55),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dotted_name, 1, .production_id = 1),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dotted_name, 2, .production_id = 3),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_imported_module_members_repeat1, 2),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_imported_module_members_repeat1, 2), SHIFT_REPEAT(43),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_imported_module_members, 1),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_imported_module_members, 2),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_member_import, 1, .production_id = 5),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_module_member_import, 3, .production_id = 10),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doc_comment_block, 1),
  [77] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_doc_comment_block_repeat1, 2), SHIFT_REPEAT(21),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_doc_comment_block_repeat1, 2),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_statement, 2, .production_id = 2),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_definition, 5, .production_id = 8),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_function_definition, 5, .production_id = 8),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_statement, 4, .production_id = 4),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_from_statement, 4, .production_id = 6),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_function_definition, 8, .production_id = 15),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_function_definition, 4, .production_id = 7),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_function_definition, 7, .production_id = 14),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_function_definition, 7, .production_id = 13),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_definition, 4, .production_id = 7),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_definition, 6, .production_id = 12),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_function_definition, 6, .production_id = 12),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_definition, 5, .production_id = 9),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_function_definition, 5, .production_id = 9),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_named_function_definition, 6, .production_id = 11),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [116] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_class_suite_repeat1, 2), SHIFT_REPEAT(51),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_class_suite_repeat1, 2),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_suite, 1),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [137] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_muonscript(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const unsigned short *)ts_parse_table,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .symbol_names = ts_symbol_names,
    .public_symbol_map = ts_symbol_map,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .field_count = FIELD_COUNT,
    .field_names = ts_field_names,
    .field_map_slices = (const TSFieldMapSlice *)ts_field_map_slices,
    .field_map_entries = (const TSFieldMapEntry *)ts_field_map_entries,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
